version: '3'

services:

  web:
    build:
      context: ./chess-web
      dockerfile: dev.Dockerfile
    volumes:
      - "./chess-web:/chess/src"
    ports:
      - "3000:4200"

  server:
    build:
      context: ./chess-api
      dockerfile: dev.Dockerfile
    volumes:
      - "./chess-api:/chess/src"
    ports:
      - "3001:5000"

      